### ISSUE TITLE
Updating the plugin to Capacitor 4.x?

### ISSUE THREAD

**Issue by radibit** [perfood/capacitor-healthkit#13]
Hey folks 👋

Thanks for your work on this plugin! I'd like to understand if you're having plans to actively maintain and further develop the plugin? If yes, do you see it feasible to support Capacitor 4.x?

**Comment by mahnuh** [comment]
Hi @radibit we are actively maintaining this plugin and we do have plans to support Capacitor 4. It might take a couple of days though, as we are pretty busy with other stuff right now.

**Comment by radibit** [comment]
Thank you for the lighting fast answer and confirmation 🙂

**Comment by mahnuh** [comment]
Hi @radibit sorry for the delay. Could you please try version 1.1.0-1 of this plugin (npm i @perfood/capacitor-healthkit@1.1.0-1) and verify that everything works as expected with Capacitor 4?

**Comment by mahnuh** [comment]
@radibit v1.2.0 has been releasend and should be compatible with Capacitor 4.

**Comment by radibit** [comment]
@mahnuh Thanks and I'll check on my end if everything works as expected.
