### ISSUE TITLE
capacitor 5 update and support for android.

### ISSUE THREAD

**Issue by Saqib92** [perfood/capacitor-healthkit#25]

**Comment by mahnuh** [comment]
Hi @Saqib92, are there problems with Capacitor 5? If so can you please provide more details?
As for Android there is a separate [plugin](https://github.com/perfood/capacitor-google-fit) for that.

**Comment by Saqib92** [comment]
No, I was going through documentation and didn't see capacitor 5 in docs. 
I have a project where we have to get Health related data from users' device.

**Comment by mahnuh** [comment]
The plugin should work with Capacitor 5, so I'm closing this issue. If you run into problems, please feel free to open a new issue with detailed information.
