### ISSUE TITLE
How to read carbohydrates, fat and proteins ?

### ISSUE THREAD

**Issue by leobenini** [perfood/capacitor-healthkit#30]
Hi perfood,
thank you for your plugin,

I need to read from healthkit the quantities of carbohydrates, total fats and proteins from the dietary.

I notice that are not managed the keys: dietaryFatTotal, dietaryCarbohydrates, dietaryProtein.

How can I do to read other types of samples from the healthkit's api?

Thank you,
Leonardo

**Comment by mahnuh** [comment]
Hi @leobenini,
we are currently working on a complete rewrite of this plugin, check the v2 branch. Dietary information currently is not on our roadmap, but feel free to open a pull request!
Manuel

**Comment by Vatanay** [comment]
@mahnuh hi. Also, we need the user's current permission status. Google fit integration would be awesome also.

edit: just saw the getAuthorizationStatus :)

**Comment by mahnuh** [comment]
Hi @Vatanay for GoogleFit we have a separate plugin.
