### ISSUE TITLE
Incompatible with capacitor 5.xx

### ISSUE THREAD

**Issue by codoffer** [perfood/capacitor-healthkit#31]
We are not able to install with the latest ionic (using capacitor 5.x)

```
Found: @capacitor/core@5.1.1 node_modules/@capacitor/core
@capacitor/core@"5.1.1" from the root project
Could not resolve dependency: peer @capacitor/core@'^4.0.0"
from @perfood/capacitor-healthkit@1.3.0
node_modules/@perfood/capacitor-healthkit
@perfood/capacitor-healthkit@'*' from the root project
```

**Comment by brunoinds** [comment]
Me too... Changing the Capacitor target on this repository is enough, or it will break it?

**Comment by mahnuh** [comment]
@brunoinds @codoffer please check [this solution](https://github.com/perfood/capacitor-healthkit/issues/23#issuecomment-1792425027) and I kindly ask to get back to me if this worked for you or not.

**Comment by codoffer** [comment]
@mahnuh It's not working. We are getting errors as attached. 

![Screenshot 2024-09-18 at 4 35 16 PM](https://github.com/user-attachments/assets/909b2eea-8686-474d-9f7d-cff29293a1f5)

**Comment by mahnuh** [comment]
Please use --legacy-peer-deps.

**Comment by codoffer** [comment]
We have tried the above solution and the package has been installed. We are getting the same error when adding to the iOS platform.

`ionic cap add ios`

I can't skip or use --legacy-peer-deps with this.

**Comment by mahnuh** [comment]
You need to use an .npmrc file for that.

**Comment by codoffer** [comment]
Thanks @mahnuh It's working with the above change.  Now we are facing issues with workout values fetching. We want to fetch below activities 

basalEnergyBurned
activeEnergyBurned
distanceCycling
distanceWalkingRunning

As your current codebase, the workout function focused on one activity only. Can you provide the facility to fetch the above activities?

Thanks in advance.

**Comment by codoffer** [comment]
@mahnuh Can you help with this?

**Comment by codoffer** [comment]
@mahnuh Can you migrate my PR - https://github.com/perfood/capacitor-healthkit/pull/41
