### ISSUE TITLE
Feature: Medications (pills)

### ISSUE THREAD

**Issue by brunoinds** [perfood/capacitor-healthkit#32]
Let's allow to read and write Medications (pills) on HealthKit.

**Comment by mahnuh** [comment]
Hi @brunoinds,
feel free to open a PR but please start out from the v2 branch. Currently I unfortunately have no free capacities to work on that.

**Comment by brunoinds** [comment]
Nice!! I have been looking through the Swift documentation about the Medications API and right now there is no native API available for this feature. So, when it is available, I will work on that to bring this feature to Capacitor.
