### ISSUE TITLE
Any plans to initiate workouts from the plugin?

### ISSUE THREAD

**Issue by reed-lawrence** [perfood/capacitor-healthkit#5]
Do you plan on wrapping methods such as HKWorkoutSession to allow a user to initiate a workout from the capacitor app?

**Comment by arnauddrain** [comment]
Hello @reed-lawrence, sorry for the late response.
We're not actively maintaining this project anymore, but feel free to submit a Pull Request and we'll review and publish it as soon as possible 🙂
